# Generated by Django 3.0.7 on 2020-07-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default="<module 'django.utils.timezone' from '/home/navaneeth/.local/lib/python3.6/site-packages/django/utils/timezone.py'>", max_length=20),
        ),
    ]
