# Generated by Django 3.0.7 on 2020-07-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0003_auto_20200712_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='CM/media/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default='2020-07-12 04:32:07.285377', max_length=50),
        ),
    ]
