# Generated by Django 3.0.7 on 2020-07-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0004_auto_20200712_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default='2020-07-12 04:41:41.113498', max_length=50),
        ),
    ]
