# Generated by Django 3.0.7 on 2020-07-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmr', '0007_auto_20200712_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
